global:
  evaluation_interval: 30s
  scrape_interval: 30s
rule_files:
- hive_alerts.yml
scrape_configs:
- job_name: hive-backend
  metrics_path: /api/metrics
  static_configs:
  - targets:
    - hive-coordinator:8000
- job_name: hive-agents
  static_configs:
  - targets:
    - 192.168.1.72:11434
  - targets:
    - 192.168.1.27:11434
  - targets:
    - 192.168.1.113:11434
